### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by rverma-dev** [SaveTheRbtz/generic-sync-map-go#1]
While I understand this is mostly a very early stage code, i tried to use this while experimenting with generics.

To my wonder I am seeing the error `fatal error: concurrent map read and map write` sometimes when I run the code and sometimes it doesn't occur. My input is same for all the runs, it seems sometime a race condition kick in and cause the exception.

The gist of code is

```
m := new(sm.MapOf[string, sm.MapOf[string, int]]). // map of map . Holds | parent | unique-child | unique-childcount
for loop {
   if _, ok := m.Load(component); !ok {      // if parent don't exists, insert parent with empty map
       m.Store(component, *new(sm.MapOf[string, int]))
    }
    apis, _ := m.Load(component)              // get child map for a parent
    count, _ := apis.Load(url)                      // get current count of child 
    apis.Store(url, count+1)                        //  increment current count
    m.Store(component, apis)                   // store the count 
}
```
@SaveTheRbtz can you help with the issue?

**Comment by SaveTheRbtz** [comment]
You have couple of load/store races in your code.  You may want to replace:
```
   if _, ok := m.Load(component); !ok {      // if parent don't exists, insert parent with empty map
       m.Store(component, *new(sm.MapOf[string, int]))
    }
```
with (I'm using [go.uber.org/atomic](https://pkg.go.dev/go.uber.org/atomic))
```
apis, _ := LoadOrStore(component, *new(sm.MapOf[string, *atomic.Uint64))
```

Also, your count load and store are racing, so you probably want to replace them with:
```
if count, loaded := apis.LoadOrStore(url, atomic.NewUint64(1)); loaded {
    count.Inc()
}
```

**Comment by rverma-dev** [comment]
Thanks a lot, your suggestions helped.
